### ISSUE TITLE
upgrade from 6.1 -> 6.2.z on rhel6 failed at executing task 'sync_tools_repos_to_upgrade'

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#131]
```
[rhel6_sat_server] Executing task 'sync_tools_repos_to_upgrade'
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/main.py", line 762, in main
    *args, **kwargs
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 425, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/upgrade-to-6.2-rhel6/upgrade/runner.py", line 62, in setup_products_for_upgrade
    clients6, clients7 = satellite6_client_setup()
  File "/home/jenkins/workspace/upgrade-to-6.2-rhel6/upgrade/client.py", line 125, in satellite6_client_setup
    host=sat_host
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 385, in execute
    multiprocessing
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 275, in _execute
    return task.run(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/upgrade-to-6.2-rhel6/upgrade/helpers/tasks.py", line 261, in sync_tools_repos_to_upgrade
    '--name {}'.format(env_name)), env_name, 'id')
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/automation_tools/satellite6/hammer.py", line 61, in get_attribute_value
    raise TypeError('hammer data is not one of type list/dict.')
TypeError: hammer data is not one of type list/dict.
```

**Comment by jyejare** [comment]
This is very sporadic issue. Could be a timing issue.

**Comment by ntkathole** [comment]
We don't have sat 6.1 rhel 6 images now.
