### ISSUE TITLE
Add support to run satellite6-upgrade with python3.6 by moving to ovirtsdk4

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/satellite6-upgrade#162]
Some background,
1) rhevm1 is now upgraded to version `4.1`
2) Current `ovirt-engine-sdk-python` being used is `3.6.8`, which still works with `rhevm1`, which is now upgraded to `4.1` but only with python2.x interpreter.
3) It appears that `ovirt-engine-sdk-python=3.6.8` does not have support for python3.x.
4) Only `ovirt-engine-sdk-python=4+` appears to have support for python3.x.

NOTE: Will move the Jenkins jobs to use `python3.6 interpreter` shortly except for the upgrade jobs because of the above-mentioned stuff.

This support is needed in `satellite6-upgrade` to provision an VM or work with templates.

UPDATE: sorry, removed the FQDN

**Comment by kbidarkar** [comment]
Currently with `Python == 3.6` and `ovirt-engine-sdk-python==4.1.7`

```
#  pip install ovirt-engine-sdk-python==4.1.7
Collecting ovirt-engine-sdk-python==4.1.7
Requirement already satisfied: pycurl>=7.19.0 in /home/kbidarka/.virtualenvs/py3-sat-upgrade/lib/python3.6/site-packages (from ovirt-engine-sdk-python==4.1.7)
Requirement already satisfied: six in /home/kbidarka/.virtualenvs/py3-sat-upgrade/lib/python3.6/site-packages (from ovirt-engine-sdk-python==4.1.7)
Installing collected packages: ovirt-engine-sdk-python
Successfully installed ovirt-engine-sdk-python-4.1.7

#  fab -u root create_rhevm_instance:kedarb_instance,robottelo-automation-rhel74,datacenter=Satellite-Engineering,quota=Default,cluster=Satellite-Engineering
Traceback (most recent call last):
  File "/home/kbidarka/.virtualenvs/py3-sat-upgrade/lib/python3.6/site-packages/fabric/main.py", line 673, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/home/kbidarka/.virtualenvs/py3-sat-upgrade/lib/python3.6/site-packages/fabric/main.py", line 174, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/home/kbidarka/git_world/satellite6-upgrade/fabfile.py", line 3, in <module>
    from upgrade.runner import ( # flake8: noqa
  File "/home/kbidarka/git_world/satellite6-upgrade/upgrade/runner.py", line 10, in <module>
    from upgrade.capsule import (
  File "/home/kbidarka/git_world/satellite6-upgrade/upgrade/capsule.py", line 11, in <module>
    from upgrade.helpers.rhevm import (
  File "/home/kbidarka/git_world/satellite6-upgrade/upgrade/helpers/rhevm.py", line 6, in <module>
    from ovirtsdk.api import API
ModuleNotFoundError: No module named 'ovirtsdk'
```

**Comment by kbidarkar** [comment]
Currently with `Python == 3.6` and `ovirt-engine-sdk-python==3.6.8.0`

```
#  pip install ovirt-engine-sdk-python==3.6.8.0
Collecting ovirt-engine-sdk-python==3.6.8.0
Requirement already satisfied: lxml>=2.2.3 in /home/kbidarka/.virtualenvs/py3-sat-upgrade/lib/python3.6/site-packages (from ovirt-engine-sdk-python==3.6.8.0)
Requirement already satisfied: pycurl>=7.19.0 in /home/kbidarka/.virtualenvs/py3-sat-upgrade/lib/python3.6/site-packages (from ovirt-engine-sdk-python==3.6.8.0)
Installing collected packages: ovirt-engine-sdk-python
Successfully installed ovirt-engine-sdk-python-3.6.8.0

#  fab -u root create_rhevm_instance:kedarb1_instance,robottelo-automation-rhel74,datacenter=Satellite-Engineering,quota=Default,cluster=Satellite-Engineering
Traceback (most recent call last):
  File "/home/kbidarka/.virtualenvs/py3-sat-upgrade/lib/python3.6/site-packages/fabric/main.py", line 673, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/home/kbidarka/.virtualenvs/py3-sat-upgrade/lib/python3.6/site-packages/fabric/main.py", line 174, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/home/kbidarka/git_world/satellite6-upgrade/fabfile.py", line 3, in <module>
    from upgrade.runner import ( # flake8: noqa
  File "/home/kbidarka/git_world/satellite6-upgrade/upgrade/runner.py", line 10, in <module>
    from upgrade.capsule import (
  File "/home/kbidarka/git_world/satellite6-upgrade/upgrade/capsule.py", line 11, in <module>
    from upgrade.helpers.rhevm import (
  File "/home/kbidarka/git_world/satellite6-upgrade/upgrade/helpers/rhevm.py", line 6, in <module>
    from ovirtsdk.api import API
  File "/home/kbidarka/.virtualenvs/py3-sat-upgrade/lib/python3.6/site-packages/ovirtsdk/api.py", line 32, in <module>
    from ovirtsdk.infrastructure.errors import UnsecuredConnectionAttemptError
  File "/home/kbidarka/.virtualenvs/py3-sat-upgrade/lib/python3.6/site-packages/ovirtsdk/infrastructure/errors.py", line 17, in <module>
    from ovirtsdk.xml import params
  File "/home/kbidarka/.virtualenvs/py3-sat-upgrade/lib/python3.6/site-packages/ovirtsdk/xml/params.py", line 89
    except ImportError, exp:
                      ^
SyntaxError: invalid syntax
```

**Comment by jyejare** [comment]
Hi, @kbidarkar , I have added the rhev4 api support and hence we can move further.

**Comment by ntkathole** [comment]
Closing this as Fixed, now requirement is ovirt-engine-sdk-python==4.2.7!
