### ISSUE TITLE
UnboundLocalError: local variable 'puppet_clients7' referenced before assignment

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/satellite6-upgrade#195]
https://github.com/SatelliteQE/satellite6-upgrade/blob/db5146c9e111a0193007d11796cb256e8c95543e/upgrade/runner.py#L68

INFO:upgrade_logging:Satellite is ready for Upgrade!
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/2b212d91/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/home/jenkins/shiningpanda/jobs/2b212d91/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/jenkins/shiningpanda/jobs/2b212d91/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6_db_upgrade_migrate/upgrade/runner.py", line 68, in setup_products_for_upgrade
    'puppet_clients7': puppet_clients7
UnboundLocalError: local variable 'puppet_clients7' referenced before assignment

**Comment by jyejare** [comment]
The referenced PR is merged and hence closing this one.
