### ISSUE TITLE
KeyError: 'puppet_clients6'

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/satellite6-upgrade#226]
https://github.com/SatelliteQE/satellite6-upgrade/blob/0b61c38fb3a8038c0367e1b75e0af9e97b89551d/upgrade/runner.py#L252

```
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/0f1aef86/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/home/jenkins/shiningpanda/jobs/0f1aef86/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/jenkins/shiningpanda/jobs/0f1aef86/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/upgrade-phase-6.4-rhel7/upgrade/runner.py", line 252, in product_upgrade
    puppet_clients6 = setup_dict['puppet_clients6']
KeyError: 'puppet_clients6'
```

**Comment by jyejare** [comment]
When is that it failed ? 
i tested it yesterday and then only we merged.

**Comment by ntkathole** [comment]
Yesterday...See upgrade phase job 61

**Comment by ntkathole** [comment]
Closing this as setup was not run and PR got merged later when automation already started. Will reopen if we face in future :+1:
