### ISSUE TITLE
satellite6_client_upgrade failed with AttributeError 

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/satellite6-upgrade#228]
https://github.com/SatelliteQE/satellite6-upgrade/blob/a604cfc72d141bf109fcbfea21e8321911237f1f/upgrade/helpers/tools.py#L178

Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/0f1aef86/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/home/jenkins/shiningpanda/jobs/0f1aef86/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/jenkins/shiningpanda/jobs/0f1aef86/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/upgrade-phase-6.4-rhel7/upgrade/runner.py", line 253, in product_upgrade
    satellite6_client_upgrade('rhel6', clients6)
  File "/home/jenkins/workspace/upgrade-phase-6.4-rhel7/upgrade/client.py", line 204, in satellite6_client_upgrade
    host=docker_vm
  File "/home/jenkins/shiningpanda/jobs/0f1aef86/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/home/jenkins/shiningpanda/jobs/0f1aef86/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/0f1aef86/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/upgrade-phase-6.4-rhel7/upgrade/client.py", line 263, in docker_clients_agent_version
    docker_execute_command(container, 'rpm -q {}'.format(agent)))
  File "/home/jenkins/workspace/upgrade-phase-6.4-rhel7/upgrade/helpers/tools.py", line 178, in version_filter
    return re.search('\d(\-\d|\.\d)*', rpm_name).group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ntkathole** [comment]
@jyejare when i dig into it, rhel 6 container was not having katello-agent package installed. Any idea?

```
# docker exec 981b5e693aecc166eabce7ef77388a444bd7e38eeb2da829078027cacbec6a71 rpm -q katello-agent
package katello-agent is not installed

# docker exec 981b5e693aecc166eabce7ef77388a444bd7e38eeb2da829078027cacbec6a71 cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.6 (Santiago)
```

**Comment by ntkathole** [comment]
This seems due to race condition during client setup

```
Activation key clientak_rhel6 found. Registering...
ERROR:  duplicate key value violates unique constraint "index_operatingsystems_on_title"
DETAIL:  Key (title)=(RedHat 6.6) already exists.
```

**Comment by ntkathole** [comment]
successful upgrade for next runs.Closing!
