### ISSUE TITLE
pycurl requirement should be installed depending on the backend

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/satellite6-upgrade#235]
```
Using cached https://files.pythonhosted.org/packages/61/06/935a3f7695079fd35ee07a23ce7b8f3ccbe9b9f9232942a5921e67f32c94/ovirt-engine-sdk-python-4.2.7.tar.gz
Collecting pycurl (from satellite6-upgrade->-r requirements.txt (line 33))
  Using cached https://files.pythonhosted.org/packages/e8/e4/0dbb8735407189f00b33d84122b9be52c790c7c3b25286826f4e1bdb7bde/pycurl-7.43.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Using curl-config (libcurl 7.53.1)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2xnqq8zc/pycurl/setup.py", line 913, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-2xnqq8zc/pycurl/setup.py", line 582, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-2xnqq8zc/pycurl/setup.py", line 99, in __init__
        self.configure()
      File "/tmp/pip-install-2xnqq8zc/pycurl/setup.py", line 316, in configure_unix
        specify the SSL backend manually.''')
    __main__.ConfigurationError: Curl is configured to use SSL, but we have not been able to determine which SSL backend it is using. Please see PycURL documentation for how to specify the SSL backend manually.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2xnqq8zc/pycurl/
```

**Comment by ntkathole** [comment]
@san7ket can we close this. FIxed via #237
