### ISSUE TITLE
Fix  pre_upgrade_system_checks for 6.2

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/satellite6-upgrade#246]
https://github.com/SatelliteQE/satellite6-upgrade/blob/fa58bbf30102b1ae4ea870825399cdeebddce4f7/upgrade/runner.py#L178

Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/6a8afd1b/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/home/jenkins/shiningpanda/jobs/6a8afd1b/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/jenkins/shiningpanda/jobs/6a8afd1b/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/upgrade-phase-6.2-rhel7/upgrade/runner.py", line 178, in product_upgrade
    pre_upgrade_system_checks(cap_hosts)
  File "/home/jenkins/workspace/upgrade-phase-6.2-rhel7/upgrade/helpers/tasks.py", line 791, in pre_upgrade_system_checks
    wait_untill_capsule_sync(capsule)
  File "/home/jenkins/workspace/upgrade-phase-6.2-rhel7/upgrade/helpers/tasks.py", line 774, in wait_untill_capsule_sync
    active_tasks = cap.content_get_sync()['active_sync_tasks']
  File "/home/jenkins/shiningpanda/jobs/6a8afd1b/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 694, in content_get_sync
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/6a8afd1b/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 117, in _handle_response
    response.raise_for_status()
  File "/home/jenkins/shiningpanda/jobs/6a8afd1b/virtualenvs/d41d8cd9/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://satellite/katello/api/capsules/2/content/sync

**Comment by ntkathole** [comment]
Upgrade-phase-6.2 Job 24
