### ISSUE TITLE
syncing latest capsule repo failed during 6.3 to 6.4 upgrade

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/satellite6-upgrade#267]
https://github.com/SatelliteQE/satellite6-upgrade/blob/e2107917151483c1b1b72d1ce767de183d5be19b/upgrade/helpers/tasks.py#L214

```
Syncing latest capsule repos in Satellite ...
INFO:upgrade_logging:Syncing latest capsule repos in Satellite ...

Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/564d526e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/home/jenkins/shiningpanda/jobs/564d526e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/jenkins/shiningpanda/jobs/564d526e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/upgrade-to-6.4-rhel7/upgrade/runner.py", line 62, in setup_products_for_upgrade
    sat_host, os_version, False if product == 'n-1' else True)
  File "/home/jenkins/workspace/upgrade-to-6.4-rhel7/upgrade/capsule.py", line 93, in satellite6_capsule_setup
    execute(sync_capsule_repos_to_upgrade, cap_hosts, host=sat_host)
  File "/home/jenkins/shiningpanda/jobs/564d526e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/home/jenkins/shiningpanda/jobs/564d526e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/564d526e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/upgrade-to-6.4-rhel7/upgrade/helpers/tasks.py", line 129, in sync_capsule_repos_to_upgrade
    _add_additional_subscription_for_capsule(ak, capsuletools_url)
  File "/home/jenkins/workspace/upgrade-to-6.4-rhel7/upgrade/helpers/tasks.py", line 299, in _add_additional_subscription_for_capsule
    scl_repo, server_repo = _sync_rh_repos_to_satellite(org)
  File "/home/jenkins/workspace/upgrade-to-6.4-rhel7/upgrade/helpers/tasks.py", line 214, in _sync_rh_repos_to_satellite
    name=rhelcontents['rhscl']['prod'], organization=org).search()[0]
IndexError: list index out of range
```

See Job 79  -  upgrade-to-6.4-rhel7

**Comment by jyejare** [comment]
@ntkathole , These 2 cherry-picked(forgotten :)) PRs should fix the issue:
https://github.com/SatelliteQE/nailgun/pull/598
https://github.com/SatelliteQE/nailgun/pull/599

**Comment by ntkathole** [comment]
@jyejare Still failing with error
```
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/564d526e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/home/jenkins/shiningpanda/jobs/564d526e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/jenkins/shiningpanda/jobs/564d526e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/upgrade-to-6.4-rhel7/upgrade/runner.py", line 62, in setup_products_for_upgrade
    sat_host, os_version, False if product == 'n-1' else True)
  File "/home/jenkins/workspace/upgrade-to-6.4-rhel7/upgrade/capsule.py", line 93, in satellite6_capsule_setup
    execute(sync_capsule_repos_to_upgrade, cap_hosts, host=sat_host)
  File "/home/jenkins/shiningpanda/jobs/564d526e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/home/jenkins/shiningpanda/jobs/564d526e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/564d526e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/upgrade-to-6.4-rhel7/upgrade/helpers/tasks.py", line 139, in sync_capsule_repos_to_upgrade
    customcontents['capsule']['prod'], capsules)
  File "/home/jenkins/workspace/upgrade-to-6.4-rhel7/upgrade/helpers/tasks.py", line 855, in add_custom_product_subscription_to_hosts
    entities.HostSubscription(host=host).add_subscriptions(
AttributeError: 'HostSubscription' object has no attribute 'add_subscriptions'

```

**Comment by ntkathole** [comment]
Issue fixed now.
