### ISSUE TITLE
docker clean up failing

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/satellite6-upgrade#289]
https://github.com/SatelliteQE/satellite6-upgrade/blob/fa58bbf30102b1ae4ea870825399cdeebddce4f7/upgrade/helpers/docker.py#L134

Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/de248335/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/main.py", line 673, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/home/jenkins/shiningpanda/jobs/de248335/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/main.py", line 174, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/home/jenkins/workspace/satellite6-upgrade-cleanup/fabfile.py", line 55, in <module>
    from upgrade_tests.helpers.existence import (
  File "/home/jenkins/workspace/satellite6-upgrade-cleanup/upgrade_tests/helpers/existence.py", line 15, in <module>
    from upgrade_tests.helpers.constants import api_const, cli_const
  File "/home/jenkins/workspace/satellite6-upgrade-cleanup/upgrade_tests/helpers/constants.py", line 11, in <module>
    class cli_const:
  File "/home/jenkins/workspace/satellite6-upgrade-cleanup/upgrade_tests/helpers/constants.py", line 24, in cli_const
    'discovery-rule' if float(to_version) >= 6.3 else 'discovery_rule',
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by ntkathole** [comment]
Fixed!
