### ISSUE TITLE
Regression from  PR 310

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/satellite6-upgrade#313]
https://github.com/SatelliteQE/satellite6-upgrade/blob/e19e6ccbae57e8df2a3e4b56402316d94dff2bc2/upgrade_tests/helpers/constants.py#L24

Upgrade helpers are used in different jobs independent of having "to_version" in environment variable.
if to_version is none, job get failed
```

Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/d2e6e553/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/main.py", line 673, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/home/jenkins/shiningpanda/jobs/d2e6e553/virtualenvs/d41d8cd9/lib/python3.6/site-packages/fabric/main.py", line 174, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/home/jenkins/workspace/satellite6-custom-certs-automation/fabfile.py", line 55, in <module>
    from upgrade_tests.helpers.existence import (
  File "/home/jenkins/workspace/satellite6-custom-certs-automation/upgrade_tests/helpers/existence.py", line 18, in <module>
    from upgrade_tests.helpers.constants import api_const, cli_const
  File "/home/jenkins/workspace/satellite6-custom-certs-automation/upgrade_tests/helpers/constants.py", line 11, in <module>
    class cli_const:
  File "/home/jenkins/workspace/satellite6-custom-certs-automation/upgrade_tests/helpers/constants.py", line 69, in cli_const
    'discovery-rule' if float(to_version) >= 6.3 else 'discovery_rule',
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by jyejare** [comment]
@ntkathole , What is the job where its failing.

**Comment by ntkathole** [comment]
See satellite6-custom-certs-automation job 30
