### ISSUE TITLE
Random failure , while running sync_capsule_repos_to_upgrade task

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/satellite6-upgrade#52]
Looks like a timing issue get_attribute_value trying to get hammer result's ,before the entity is created

```
Executing task 'sync_capsule_repos_to_upgrade'
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/upgrade-to-6.2-rhel6/upgrade/runner.py", line 60, in setup_products_for_upgrade
    sat_host, os_version, False if product == 'n-1' else True)
  File "/home/jenkins/workspace/upgrade-to-6.2-rhel6/upgrade/capsule.py", line 69, in satellite6_capsule_setup
    execute(sync_capsule_repos_to_upgrade, cap_hosts, host=sat_host)
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 386, in execute
    multiprocessing
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 276, in _execute
    return task.run(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/upgrade-to-6.2-rhel6/upgrade/helpers/tasks.py", line 171, in sync_capsule_repos_to_upgrade
    activation_key, '1', product_name)
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 170, in __call__
    return self.run(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/automation_tools/satellite6/hammer.py", line 322, in hammer_activation_key_add_subscription
    organization_id, product_name)
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/automation_tools/satellite6/hammer.py", line 396, in get_product_subscription_id
    'id')
  File "/home/jenkins/shiningpanda/jobs/f215f424/virtualenvs/d41d8cd9/lib/python2.7/site-packages/automation_tools/satellite6/hammer.py", line 52, in get_attribute_value
    'result to get attribute value'.format(search_key))
KeyError: 'Unable to find search_key capsule6_latest in given hammer result to get attribute value'
```

**Comment by jyejare** [comment]
This is specially been observed on RHEL6 machine, Also the issue is very sporadic.

**Comment by jyejare** [comment]
Observation 1: The sync of contents of new repo 'capsule6_latest' has seen this error in dynflow:
```
: Actions::Pulp::Repository::Sync (waiting for Pulp to finish the task) [ 2541.17s / 43.77s ]
```

Also I see that the pulp is running fine in bg.

**Comment by san7ket** [comment]
I see same issue , on different repo,

```
Syncing Tools repos of rhel6 in Satellite..
 Executing task 'sync_tools_repos_to_upgrade'
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-upgrader@2/upgrade/runner.py", line 63, in setup_products_for_upgrade
    clients6, clients7 = satellite6_client_setup()
  File "/home/jenkins/workspace/satellite6-upgrader@2/upgrade/client.py", line 118, in satellite6_client_setup
    host=sat_host
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 386, in execute
    multiprocessing
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 276, in _execute
    return task.run(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-upgrader@2/upgrade/helpers/tasks.py", line 255, in sync_tools_repos_to_upgrade
    '--name {}'.format(env_name)), env_name, 'id')
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/automation_tools/satellite6/hammer.py", line 61, in get_attribute_value
    raise TypeError('hammer data is not one of type list/dict.')
TypeError: hammer data is not one of type list/dict.
```

**Comment by san7ket** [comment]
Pulp task Deadlock, some steps to try avoiding this situation.
To free up any halted or deadlocked worker's.

`for i in pulp_resource_manager pulp_workers pulp_celerybeat; do service $i restart; done`

The above restart , would halt the stuck tasks and start new tasks
Since the old tasks would be killed , automation would think it has completed and move further to attach subscriptions .
To avoid adding subcription before publishing.
Also, to run subscription manager on capsule once again after the satellite is upgraded or before running yum update on capsule
