### ISSUE TITLE
6.2 -> 6.3 upgrade is being affected by this issue while running `sync_capsule_repos_to_upgrade`

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#81]
```
] Executing task 'sync_capsule_repos_to_upgrade'
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/main.py", line 762, in main
    *args, **kwargs
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 425, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-upgrader/upgrade/runner.py", line 63, in setup_products_for_upgrade
    clients6, clients7 = satellite6_client_setup()
  File "/home/jenkins/workspace/satellite6-upgrader/upgrade/client.py", line 85, in satellite6_client_setup
    int(clients_count)/2,
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by sghai** [comment]
@jyejare : Please take a look and fix this on priority..

**Comment by jyejare** [comment]
This issue happened due to missing clients_count environment variable, so now check is added to client setup part to handle this kind of issue.

PR #82  raised

**Comment by jyejare** [comment]
PR #82 is already merged and hence closing this issue
